#!/bin/bash

app_name=${1:-test-concourse-ci}

set -ux

pushd build
  workdir=$(pwd)
  session_key=$workdir/session-key
  tsa_key=$workdir/tsa-key
  worker_key=$workdir/worker-key
popd

worker_fingerprint=$(ssh-keygen -lf $worker_key | cut -d ' ' -f 2)

heroku apps:destroy -a $app_name -c $app_name
doctl compute droplet delete $app_name
doctl compute ssh-key delete $worker_fingerprint
