#!/bin/bash

set -eux

workdir=`pwd`
session_key=$workdir/session-key
tsa_key=$workdir/tsa-key
worker_key=$workdir/worker-key

./concourse worker \
  --work-dir /opt/concourse/worker \
  --tsa-host $(cat hostname) \
  --tsa-public-key ${tsa_key}.pub \
  --tsa-worker-private-key $worker_key

